export const scores = [
    { username: "Muhsina", score: 1 },
    { username: "Aamilah", score: 2 },
    { username: "Tom", score: 4 },
    { username: "Will", score: 2 },
    { username: "Naimah", score: 5 },
    { username: "Mo", score: 5 },
    { username: "Jane", score: 2 },
    { username: "Naim", score: 1 },
    { username: "Harry", score: 3 },
    { username: "Bob", score: 1 },
    { username: "Dick", score: 1 },
    { username: "John", score: 3 },
    { username: "Zahra", score: 3 },
    { username: "Is\'haaq", score: 5 },
    { username: "Betty", score: 4 },
    { username: "James", score: 3 },
    { username: "Tamjid", score: 4 },
];
